### ISSUE TITLE
test_full Cannot access file fastq

### ISSUE THREAD

**Issue by jambler24** [nf-core/ampliseq#698] opened 2024-02-01 17:55 UTC
### Description of the bug

When running the test_full profile, the following error is seen:
`ERROR ~ Cannot access file: /ngi-igenomes/test-data/ampliseq/SRR10070130_1.fastq.gz
`

### Command used and terminal output

```console
nextflow run nf-core/ampliseq -latest -resume -profile test_full,docker --outdir ./results/test_2/ --picrust
```

### Relevant files

[nextflow.log](https://github.com/nf-core/ampliseq/files/14129075/nextflow.log)

### System information

nf-core/ampliseq v2.8.0-gf3c97e1
N E X T F L O W  ~  version 23.10.1
Intel mac

**Comment by d4straub** [comment] 2024-02-02 07:34
Hi there, I just tested with `-profile test_full` myself and it seems fine. The files in question are on an amazon s3 storage, that really should not be a problem.

I found in your log file 
`Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 90Y1M4SDXCZ2JDQ2; S3 Extended Request ID: i2GFgVAWldXstAxHeLaBjsPGcX+nNzf/w/RjN4mRGrVzwAkW1ebUOQVHU3kJv6KmRIYm4++7nhM=; Proxy: null)`
That might be the issue? You seem to have an AWS Access Key Id provided (that isnt needed afaik) that isnt valid. Removing that key may do it. I have no idea of AWS computing/files though, so you might want to look into nf-core slack to get further advice. The problem seems to me not related to this pipeline, so I close it for now.
Please open another issue if you encounter another problem.

**Closed by d4straub** 2024-02-02 07:34 UTC
Labels: bug
