### ISSUE TITLE
Add greengenes2 2022.10 support to Ampliseq

### ISSUE THREAD

**Issue by MatthewJM96** [nf-core/ampliseq#664] opened 2023-11-28 17:42 UTC
Include an additional option for qiime_ref_taxonomy (greengenes2022) that adds support for greengenes2 database.

**Comment by d4straub** [comment] 2023-11-29 07:22
Seems to be a duplicate of https://github.com/nf-core/ampliseq/issues/658, just here a bit more specific (with QIIME2).

**Closed** 2023-11-29 07:43 UTC
