### ISSUE TITLE
Strategy to correctly handle ch_fastq_trimmed channel

### ISSUE THREAD

**Issue by DiegoBrambilla** [nf-core/ampliseq#96] opened 2019-07-25 11:33 UTC
Dear all,
Greetings, I am working now on preparing a .nf script that will allow to choose [r-dada2](http://benjjneb.github.io/dada2/) for denoising reads:
[until_cutadapt.nf.txt](https://github.com/nf-core/ampliseq/files/3431207/until_cutadapt.nf.txt)
Such script is identical to `main.nf` up to line 518 (until the multiqc process). After that I am planning to introduce four different processes, one for each kind of R script from [eemis-dada2](https://github.com/erikrikarddaniel/eemisdada2):

1.     `dada2filter`: quality and length trimming
2.     `dada2errmodels`: calculation of error models from the data
3.     `dada2cleanNmerge`: sequence correction and merge
4.     `dada2bimeras`: filter bimeras, create final tables

So far execution has failed at the dada2filter step. These are the command I used:
`$ nextflow run until_cutadapt.nf -profile test,docker`

I have introduced the first step, process dada2filter, from line 518 of the attached until_Cutadapt.nf:
```
process dada2filter {

               tag "${pair_id}"
               publishDir "${params.outdir}/dada2filter", mode: 'copy',
                       saveAs: {filename ->
                       if (filename.indexOf(".out") == -1) "logs/$filename"
                       else if(params.keepIntermediates) filename
                       else null}

               input:
               set val(pair_id), file(reads) from ch_fastq_trimmed2

               output:
               file "dada2filter/*.*" into ch_fastq_dada2filter

               script:
               """
               dada2filter --verbose --trimleft=8,8 --trunclen=290,210 \
               --filterdir=dada2filter --fwdmark=trimmed/${reads[0]} --revmark=trimmed/${reads[0]} \
               >dada2filter.out 2>&1
               """
 }
```
This is the same strategy used for the process cutadapt (starting from line 438 of main.nf) and it doesn't work, most likely because the channels ch_read_pairs and ch_fastq_trimmed have different kind of objects.

Could you please help me setting ch_fastq_trimmed properly?

ch_fastq_trimmed is one of the two output channels from the process cutadapt, while ch_read_pairs has been created earlier in the script (from line 324 of `main.nf`):

```
324                 //Test input for single sequencing runs, profile = test
325
326                 Channel
327                         .from(params.readPaths)
328                         .map { row -> [ row[0], [file(row[1][0]), file(row[1][1])]] }
329                         .ifEmpty { exit 1, "params.readPaths was empty - no input files supplied" }
330                         .into { ch_read_pairs; ch_read_pairs_fastqc; ch_read_pairs_name_check }
```
here is dada2filter help page:
```
Options:
        --indir=INDIR
                Input directory, default current directory.

        --filterdir=FILTERDIR
                Directory for quality truncated reads, default "filtered". Will be created if it does not exist.

        --fwdmark=FWDMARK
                Name pattern to identify forward reads in file names, default ".r1".

        --maxee=MAXEE
                Maximum number of expected errors in sequences, comma-separated pair for forward and reverse, default Inf.

        --minq=MINQ
                minQ option in fastqPairedFilter() call. Default 0.

        --revmark=REVMARK
                Name pattern to identify reverse reads in file names, default ".r2".

        --rmphix
                Remove phiX sequences. Currently fails (recursion in function call?)

        --trimleft=TRIMLEFT
                Comma separated pair of values for left truncation of forward and reverse reads respectively. Default "0,0".

        --trunclen=TRUNCLEN
                Comma separated pair of values for truncation position for forward and reverse reads respectively. No default, mandatory

        --truncq=TRUNCQ
                truncQ option in fastqPairedFilter() call. Default 2.

        -v, --verbose
                Print progress messages

        -V, --version
                Print version of script and DADA2 library

        -h, --help
                Show this help message and exit
```

I already have dada2filter in my $PATH as I have set it according to [instructions](https://github.com/erikrikarddaniel/eemisdada2#installation), but it should be possible to run it from `bin/` as an external script, as suggested by Daniel Straub on issue#94. to run dada2filter I've created a conda environment and I have exported it in the attached [R-dada2_env.txt](https://github.com/nf-core/ampliseq/files/3431201/R-dada2_env.txt) . you can recreate it with
`$ conda create --name <env> --file R-dada2_env.txt`

It would be also nice to set a log file the same way it was done with cutadapt process, something like this:
```
               output:
               [...]
               file "dada2filter_log.txt" into ch_fastq_dada2filter_log
               script:
               """
               [...]
               {reads[0]} ${reads[1]} > dada2filter_log.txt
```
If we want to include such processes in main.nf, can you suggest a way to set parameters and if/else conditions to include the dada2-related processes?

Thank you, I am in your care

**Comment by d4straub** [comment] 2019-07-26 11:47
Hi, that are too many problems and questions to answer without checking your whole code. Also, you did not give the error message. Hard to troubleshoot like this. I recommend working in a github repo, this might make things easier and reproducible.

I had a short look at the script and your input channel `ch_fastq_trimmed2` is empty, you need to fill it first. There are countless examples in main.nf how to do that.

**Comment by DiegoBrambilla** [comment] 2019-07-26 13:49
Hello,
Appreciate the feedback. Here I provide further information to enhance reproducibility:
- The code `until_cutadapt.nf` can be freely consulted at [this forked github repo](https://github.com/DiegoBrambilla/rrna-ampliseq/tree/dev).

- I mistakenly wrote `ch_fastq_trimmed2`instead of `ch_fastq_trimmed` (output channel of `process cutadapt`) as input channel for `process dada2filter`, my bad. 
After applying the aforementioned correction to `until_cutadapt.nf` and activating the conda environment (see my previous thread on how to recreate it), the command line `$ nextflow run until_cutadapt.nf -profile test,docker` produces the following error message:
```
N E X T F L O W  ~  version 19.04.1
Launching `until_cutadapt.nf` [awesome_curran] - revision: 5a239192ca
[2m----------------------------------------------------
	                                ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
	                                `._,._,'
  nf-core/ampliseq v1.0.0
----------------------------------------------------
Pipeline Name     : nf-core/ampliseq
Run Name          : awesome_curran
Reads             : data/*_R{1,2}_001.fastq.gz
Data Type         : Paired-End
Max Resources     : 6 GB memory, 2 cpus, 2d time per job
Container         : docker - nfcore/ampliseq:1.0.0
Output dir        : ./results
Launch dir        : /home/dibrab/dev/rrna-ampliseq
Working dir       : /home/dibrab/dev/rrna-ampliseq/work
Script dir        : /home/dibrab/dev/rrna-ampliseq
User              : dibrab
Config Profile    : test,docker
Config Description: Minimal test dataset to check pipeline function
[2m----------------------------------------------------
######## WARNING: No DADA2 cutoffs were specified, therefore reads will be truncated where median quality drops below 25.
The chosen cutoffs do not account for required overlap for merging, therefore DADA2 might have poor merging efficiency or even fail.
[warm up] executor > local
executor >  local (11)
executor >  local (11)
executor >  local (11)
executor >  local (11)
[8c/4c30c9] process > get_software_versions [100%] 1 of 1 ✔
executor >  local (11)
executor >  local (11)
[8c/4c30c9] process > get_software_versions [100%] 1 of 1 ✔
[b4/34af96] process > fastqc                [100%] 4 of 4 ✔
[53/14ec54] process > trimming              [100%] 4 of 4 ✔
[42/8315fa] process > dada2filter           [100%] 2 of 2, failed: 2
[0;35m[nf-core/ampliseq]null Pipeline completed with errors
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
ERROR ~ Error executing process > 'dada2filter (/home/dibrab/dev/rrna-ampliseq/work/8c/29c9bfca34ff0649a633b915bb33ce/trimmed/1_S103_L001_R1_001.fastq.gz)'

Caused by:
  Process `dada2filter (/home/dibrab/dev/rrna-ampliseq/work/8c/29c9bfca34ff0649a633b915bb33ce/trimmed/1_S103_L001_R1_001.fastq.gz)` terminated with an error exit status (127)

Command executed:

  dada2filter --verbose --trimleft=8,8 --trunclen=290,210 		--filterdir=dada2filter --fwdmark=trimmed/1_S103_L001_R2_001.fastq.gz --revmark=trimmed/1_S103_L001_R2_001.fastq.gz 		>dada2filter.out 2>&1

Command exit status:
  127

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

Work dir:
  /home/dibrab/dev/rrna-ampliseq/work/c7/ab00de54b48849fce8f7bc196e27be

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```
I had to halt the script because the dada2filter task was pending for an indefinte amount of time.
It is clear that the error concerns `process dada2filter`, especially regarding the way input files are called (same file called twice). This is because the script `until_cutadapt.nf` at line 537 follows the strategy used in line 459 for `process cutadapt` to call input objects, but the input channels involved (`ch_read_pairs` and `ch_fastq_trimmed`) are differentl. I require to set ch_fastqc_trimmed properly, thus leading to the issue at hand.

- Apologies for the numerous questions. I brought several topics in one issue as as they are all related to the same step. Clearly, the issue related to ch_fastq_trimmed needs to be prioritized.
After studying the processes in `main.nf`, I found a solution in line 324 of `until_cutadapt.nf` /`/Test input for single sequencing runs, profile = test`, I tried editing the channel `ch_fastq_trimmed` with the same `map` function as in line 328 but without success. I kindly require a world of advice to understand how the parameters from line 323 (from unil_cutadapt.nf or main.nf) were defined, and   how the `map` function in line 328 (from unil_cutadapt.nf or main.nf) works to handle `ch_fastq_trimmed`. I would be gratefult for any suggestion on how to proceed with `process dada2filter`.

Please bear with me as I am willing to contribute, although new to nextflow, and cannot improve without your kind feedback.

Thank you for your time, looking forward to hearing from you.

**Comment by d4straub** [comment] 2019-07-29 10:25
There is no `process cutadapt`, probably you mean trimming.
The error message does not really help here for that particular problem.

Here my take:
Input for `process dada2filter` is `ch_fastq_trimmed` and expects `set val(pair_id), file(reads)`, however it it filled with `file "trimmed/*.*"` only. No `val(pair_id)`.

So change for `process trimming_multi` and `process trimming` the output, from
```
			output:
			file "trimmed/*.*" into (ch_fastq_trimmed, ch_fastq_trimmed_manifest)
			file "cutadapt_log_*.txt" into ch_fastq_cutadapt_log
```
to
```
			output:
			set val(pair_id), file("trimmed/*.*") into ch_fastq_trimmed
			file "trimmed/*.*" into ch_fastq_trimmed_manifest
			file "cutadapt_log_*.txt" into ch_fastq_cutadapt_log
```

Also, you called twice the same file in the script of `process dada2filter`, change 
```
		script:
		"""
		dada2filter --verbose --trimleft=8,8 --trunclen=290,210 \
		--filterdir=dada2filter --fwdmark=trimmed/${reads[0]} --revmark=trimmed/${reads[0]} \
		>dada2filter.out 2>&1 
		"""
```
to
```
		script:
		"""
		dada2filter --verbose --trimleft=8,8 --trunclen=290,210 \
		--filterdir=dada2filter --fwdmark=trimmed/${reads[0]} --revmark=trimmed/${reads[1]} \
		>dada2filter.out 2>&1 
		"""
```

The output of `process dada2filter` might be wrong as well, but I cant say for sure.

**Comment by d4straub** [comment] 2019-07-29 10:29
For small test runs and exploring the concepts of input/outputs or the [map operator](https://www.nextflow.io/docs/latest/operator.html#map), you might find the [nextflow console](https://www.nextflow.io/blog/2015/introducing-nextflow-console.html) helpful.

**Comment by DiegoBrambilla** [comment] 2019-07-29 11:46
Greetings,
thanks for helping despite some mistakes of mine. Your diagnosis was spot-on and I believe it is the proper way of proceeding.

After applying the changes you suggested I am still receiving the same error message as above.
I see in [this thread](https://stackoverflow.com/questions/48685667/what-does-docker-mean-when-it-says-memory-limited-without-swap) that the warning about memory limited without swap is related to Docker settings.
Since I received such error only after the introduction of process dad2filter, not before, I speculate it has something to do with running the Rscripts from eemis-dada2.

Maybe loading a conda environment with all of the dependences is not the right way to go.

Maybe the dependencies need to be already present in the docker image. That is,  Docker during the building step needs to retrieve all of the dependencies, including those needed by the external R scripts, from the file environment.yml.

I am grateful for your supervision, it made the testing easier also thanks to mentioning the nextflow console.

**Comment by d4straub** [comment] 2019-07-29 12:05
For reproducible analysis, all software dependencies have to be in the environment.yml so they end up in the singularity/docker containers that are available via nf-core.

Dont get me wrong, but why do you need that scripts anyway? As far as I can see they aren't for PacBio analysis anyway. PacBio analysis is supported in DADA2 since [v1.10](https://benjjneb.github.io/dada2/ReleaseNotes_1_10.html) released in May 2018 but the [scripts](https://github.com/erikrikarddaniel/eemisdada2/tree/master/src/R) were last edited August 2017 and I cant find in these scripts the `PacBioErrfun` that is recommended for PacBio.

**Comment by DiegoBrambilla** [comment] 2019-07-29 16:21
Much obliged.

Using the eemis-dada2 scripts is a way to avoid including all of that wall of text inside the main nextflow script. My boss is confident that issues like compatibility with PacBio reads can be addressed with a few adjustments of said scripts. The documentation for PacBio you advised will serve the purpose.

**Comment by d4straub** [comment] 2019-08-10 08:59
Looking forward to your implementation, but that specific issue might be resolved.

**Closed by d4straub** 2019-08-10 08:59 UTC
