### ISSUE TITLE
Add GBIF adapted CO1 database

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#472] opened 2022-08-30 15:05 UTC
### Description of feature

@johnne is working on making a version of the CO1 database better adapted to the GBIF backbone taxonomy. When that is available, make sure it's selectable in Ampliseq.

**Comment by johnne** [comment] 2022-09-15 20:49
The database is up now at https://scilifelab.figshare.com/articles/dataset/COI_reference_sequences_from_BOLD_DB/20514192

**Comment by johnne** [comment] 2022-09-18 19:50
@erikrikarddaniel 
How was it now with taxonomic ranks used in ampliseq? I see the finished `assignTaxonomy.fna` file has _e.g._ `Bacteria;Bacteria;Firmicutes;Bacilli;Staphylococcales;Staphylococcaceae;Staphylococcus` as the header so it's using taxlevels `"Domain", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"`. The custom coidb has `"Kingdom", "Phylum", "Class","Order","Family","Genus","Species"` as taxlevels. So should we aim to create a `assignTaxonomy.fna` file that duplicates the `Kingdom` value to `Domain` or instead use the database with `--dada_assign_taxlevels` that I see in the documentation?

Cheers,
John

**Comment by erikrikarddaniel** [comment] 2022-09-19 05:12
I think it would be best to add a `taxlevels` entry in the `conf/ref_databases.config`; see e.g. the `midori2-co1` entry.

**Comment by johnne** [comment] 2022-10-05 19:48
@erikrikarddaniel @jtangrot 
I'm a little unsure on how to use the `fmtscript` part of the database entries in the workflow. Does it have to be a shell script, or can it be a python script in the `bin/` folder? And do you have suggestion for how to test if/how such a script works within the workflow?

**Comment by erikrikarddaniel** [comment] 2022-10-07 08:06
It can, AFAIK, be any kind of script but it will be executed by the current container, so the interpreter needs to be in that and findable by whatever you have in `#!`.
The best test is to add a test for the database you're adding. Add a config file, include that in `nextflow.config` and add to `.github/workflows/ci.yml`.

**Comment by johnne** [comment] 2022-10-12 03:51
I wasn't able to use a python script because python is not included in the ubuntu:20.04 image used for the `FORMAT_TAXONOMY` process. 

I suggest adding a `container` keyword to the `ref_databases.config` file that allows to use any container for the formatting script. See [this commit](https://github.com/NBISweden/ampliseq/pull/2/commits/c9e27c7432cdacd69133b664f950121de05e57ea)

**Comment by d4straub** [comment] 2022-10-12 07:11
If using that container keyword works fine so far this seems to me as a valid option. However, that would need to be also working for conda & singularity, that might complicate things?
Alternatively, the ubuntu container isnt set in stone and you could have a look for another lightweight container that includes both, python and bash. That way one container would serve it all.

**Comment by erikrikarddaniel** [comment] 2022-10-12 07:22
I agree with my namesake, and was perhaps leaning towards relying on one image that includes all, which means both python and bash, but also sed. Not working with singularity would of course be a show stopper.

**Comment by johnne** [comment] 2022-10-12 08:07
It's probably not too difficult to make it work for singularity as well (it works already for conda) it's more that my groovy/nextflow skills are limited still. But having a universal image sounds better. I'll see what I can find. Is there a specific reason you're pulling singularity images from https://depot.galaxyproject.org/singularity/?

**Comment by johnne** [comment] 2022-10-12 08:24
@d4straub How lightweight does the container have to be? Of course it has to contain bash, so the slimmest python containers are out. But I see nextflow also relies on the `ps` command which isn't included in some of the slightly bigger (~ 110M) containers that *do*  contain bash. The `python:3.7` container seems to work though, but it's 900M.

**Comment by johnne** [comment] 2022-10-18 05:34
It works with `quay.io/biocontainers/python:3.8.3` for docker. However, I don't feel confident in getting all checks to work, see https://github.com/NBISweden/ampliseq/pull/2.

**Comment by d4straub** [comment] 2022-10-19 08:57
In the meantime 
- nf-core tools had an update --> nf-core linting fails in your fork (nf-core/ampliseq dev branch had its update and is passing)
- nextflow had an update --> ugly warnings about process names
- nf-core/ampliseq dev branch had updates that you seem not to have pulled yet

but `nextflow run nf-core/ampliseq -r dev -profile test,singularity` still (newest nextflow version) works locally for me (despite warnings) and `nextflow run nf-core/ampliseq -r dev -profile test_iontorrent,singularity` is also fine. Just confirmed. Not sure that helps though...

**Comment by d4straub** [comment] 2023-02-07 15:02
That seems to be completed by #518 and #534  ?

**Comment by erikrikarddaniel** [comment] 2023-02-07 16:26
I would say so, yes.

**Comment by d4straub** [comment] 2023-02-08 09:21
Then I'll close it for now.

**Closed by d4straub** 2023-02-08 09:21 UTC
Labels: enhancement
