### ISSUE TITLE
Error executing process > 'make_SILVA_132_16S_classifier (1)

### ISSUE THREAD

**Issue by MonicaSteffi** [nf-core/ampliseq#169] opened 2020-10-19 12:25 UTC
Hi,
I also encountered the similar issue. I used the following commad:

`nextflow run -r 1.1.0 nf-core/ampliseq -profile docker --reads data --FW_primer CCTACGGGNGGCWGCAG --RV_primer GACTACHVGGGTATCTAATCC --trunclenf 250 --trunclenr 240 --outdir results-CRC_modified_1 --multipleSequencingRuns --metadata 30092020_multisequence.txt `

I got the following error and I have attached the log file also

```
nf-core/ampliseq execution completed unsuccessfully!

The exit status of the task that caused the workflow execution to fail was: 0.

The full error message was:

Error executing process > 'make_SILVA_132_16S_classifier (1)'

Caused by:
  /media/adminuser/DATA/nfcore/work/e4/17f26616ecc372ff296a8f2c34573c/SILVA_132_QIIME_release
```

I have shared the logfile through google doc.

[https://docs.google.com/document/d/1_45htBHESH-j9HUSOf3JF8WdjTcYcxHEXbYHh6shmC8/edit?usp=sharing](url)

Thank you in advance

**Comment by d4straub** [comment] 2020-10-19 12:41
Hi there,

The message `java.nio.file.AccessDeniedException: /media/adminuser/DATA/Sandra/nfcore/work/e4/17f26616ecc372ff296a8f2c34573c/SILVA_132_QIIME_release` suggests that there was a fault in access. This could be missing access rights or file system hiccups. To address the first, speak with your system admin, to make sure its not the second, resume the pipeline using your previous execution command and add `-resume`. Because this might have happened during file download, i.e. internet activity, you can also download the [database](https://www.arb-silva.de/fileadmin/silva_databases/qiime/Silva_132_release.zip) and use `--reference_database [path/to/file] -resume` and see if this solved the problem.

Let me know if this helped!

**Comment by d4straub** [comment] 2020-11-26 13:45
Since there was no further comment, I'll assume the problem is fixed and close this issue. Please do not open another issue.

**Closed by d4straub** 2020-11-26 13:45 UTC
